//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações a este ficheiro poderão provocar um comportamento incorrecto e perder-se-ão se
//     o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monster.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Monster.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] boyPlayerPic {
            get {
                object obj = ResourceManager.GetObject("boyPlayerPic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] draco_stage1_battle {
            get {
                object obj = ResourceManager.GetObject("draco_stage1_battle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] draco_stage1_hurt {
            get {
                object obj = ResourceManager.GetObject("draco_stage1_hurt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] draco_stage1_inventory {
            get {
                object obj = ResourceManager.GetObject("draco_stage1_inventory", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] draco_stage1_sleeping {
            get {
                object obj = ResourceManager.GetObject("draco_stage1_sleeping", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] draco_stage2_battle {
            get {
                object obj = ResourceManager.GetObject("draco_stage2_battle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] draco_stage2_hurt {
            get {
                object obj = ResourceManager.GetObject("draco_stage2_hurt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] draco_stage2_inventory {
            get {
                object obj = ResourceManager.GetObject("draco_stage2_inventory", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] draco_stage2_sleeping {
            get {
                object obj = ResourceManager.GetObject("draco_stage2_sleeping", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] draco_stage3_battle {
            get {
                object obj = ResourceManager.GetObject("draco_stage3_battle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] draco_stage3_hurt {
            get {
                object obj = ResourceManager.GetObject("draco_stage3_hurt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] draco_stage3_inventory {
            get {
                object obj = ResourceManager.GetObject("draco_stage3_inventory", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] draco_stage3_sleeping {
            get {
                object obj = ResourceManager.GetObject("draco_stage3_sleeping", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] girlPlayerPic {
            get {
                object obj = ResourceManager.GetObject("girlPlayerPic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] grifo_stage1_battle {
            get {
                object obj = ResourceManager.GetObject("grifo_stage1_battle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] grifo_stage1_hurt {
            get {
                object obj = ResourceManager.GetObject("grifo_stage1_hurt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] grifo_stage1_inventory {
            get {
                object obj = ResourceManager.GetObject("grifo_stage1_inventory", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] grifo_stage1_sleeping {
            get {
                object obj = ResourceManager.GetObject("grifo_stage1_sleeping", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] grifo_stage2_battle {
            get {
                object obj = ResourceManager.GetObject("grifo_stage2_battle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] grifo_stage2_hurt {
            get {
                object obj = ResourceManager.GetObject("grifo_stage2_hurt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] grifo_stage2_inventory {
            get {
                object obj = ResourceManager.GetObject("grifo_stage2_inventory", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] grifo_stage2_sleeping {
            get {
                object obj = ResourceManager.GetObject("grifo_stage2_sleeping", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] grifo_stage3_battle {
            get {
                object obj = ResourceManager.GetObject("grifo_stage3_battle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] grifo_stage3_hurt {
            get {
                object obj = ResourceManager.GetObject("grifo_stage3_hurt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] grifo_stage3_inventory {
            get {
                object obj = ResourceManager.GetObject("grifo_stage3_inventory", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] grifo_stage3_sleeping {
            get {
                object obj = ResourceManager.GetObject("grifo_stage3_sleeping", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] otherPlayerPic {
            get {
                object obj = ResourceManager.GetObject("otherPlayerPic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] red_hurt {
            get {
                object obj = ResourceManager.GetObject("red_hurt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] red_normal {
            get {
                object obj = ResourceManager.GetObject("red_normal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] siren_stage1_battle {
            get {
                object obj = ResourceManager.GetObject("siren_stage1_battle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] siren_stage1_hurt {
            get {
                object obj = ResourceManager.GetObject("siren_stage1_hurt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] siren_stage1_inventory {
            get {
                object obj = ResourceManager.GetObject("siren_stage1_inventory", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] siren_stage2_battle {
            get {
                object obj = ResourceManager.GetObject("siren_stage2_battle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] siren_stage2_hurt {
            get {
                object obj = ResourceManager.GetObject("siren_stage2_hurt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] siren_stage2_inventory {
            get {
                object obj = ResourceManager.GetObject("siren_stage2_inventory", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] siren_stage3_battle {
            get {
                object obj = ResourceManager.GetObject("siren_stage3_battle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] siren_stage3_hurt {
            get {
                object obj = ResourceManager.GetObject("siren_stage3_hurt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] siren_stage3_inventory {
            get {
                object obj = ResourceManager.GetObject("siren_stage3_inventory", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] skull_hurt {
            get {
                object obj = ResourceManager.GetObject("skull_hurt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] skull_normal {
            get {
                object obj = ResourceManager.GetObject("skull_normal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] tauro_stage1_battle {
            get {
                object obj = ResourceManager.GetObject("tauro_stage1_battle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] tauro_stage1_hurt {
            get {
                object obj = ResourceManager.GetObject("tauro_stage1_hurt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] tauro_stage1_inventory {
            get {
                object obj = ResourceManager.GetObject("tauro_stage1_inventory", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] tauro_stage2_battle {
            get {
                object obj = ResourceManager.GetObject("tauro_stage2_battle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] tauro_stage2_hurt {
            get {
                object obj = ResourceManager.GetObject("tauro_stage2_hurt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] tauro_stage2_inventory {
            get {
                object obj = ResourceManager.GetObject("tauro_stage2_inventory", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] tauro_stage3_battle {
            get {
                object obj = ResourceManager.GetObject("tauro_stage3_battle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] tauro_stage3_hurt {
            get {
                object obj = ResourceManager.GetObject("tauro_stage3_hurt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] tauro_stage3_inventory {
            get {
                object obj = ResourceManager.GetObject("tauro_stage3_inventory", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] VCR_OSD_MONO_1_001 {
            get {
                object obj = ResourceManager.GetObject("VCR_OSD_MONO_1.001", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
